home:
  pattern:  /
  defaults: { _controller: StintChoreBundle:Default:home }


chorelist_show:
  pattern:  /list/{id}
  defaults: { _controller: StintChoreBundle:ChoreList:show }
  requirements:
    id: \d+

chorelist_create:
  pattern:  /list/create
  defaults: { _controller: StintChoreBundle:ChoreList:create }
  requirements:
    _method: POST


user_show:
  pattern:  /user/{id}
  defaults: { _controller: StintChoreBundle:User:show }
  requirements:
    id: \d+

user_create:
  pattern:  /user/create
  defaults: { _controller: StintChoreBundle:User:create }
  requirements:
    _method: POST


chore_new:
  pattern:  /{listId}/new
  defaults: { _controller: StintChoreBundle:Chore:new }
  requirements:
    listId: \d+

chore_show:
  pattern:  /chore/{id}
  defaults: { _controller: StintChoreBundle:Chore:show }
  requirements:
    id: \d+

chore_delete:
  pattern:  /chore/delete/{id}
  defaults: { _controller: StintChoreBundle:Chore:delete }
  requirements:
    id: \d+

chore_assign:
  pattern:  /chore/assign/{choreId}/{userId}
  defaults: { _controller: StintChoreBundle:Chore:assign }
  requirements:
    choreId: \d+
    userId: \d+

chore_unassign:
  pattern:  /chore/unassign/{choreId}/{userId}
  defaults: { _controller: StintChoreBundle:Chore:unassign }
  requirements:
    choreId: \d+
    userId: \d+