Stint\ChoreBundle\Entity\Chore:
  properties:
    description:
      - NotBlank: ~
      - MaxLength: 255
    period:
      - NotBlank: ~
    frequency:
      - NotBlank: ~
    start_date:
      - NotBlank: ~

Stint\ChoreBundle\Entity\ChoreList:
  properties:
    name:
      - NotBlank: ~
      - MaxLength: 255

Stint\ChoreBundle\Entity\User:
  properties:
    name:
      - NotBlank: ~
      - MaxLength: 255
    email:
      - MaxLength: 255
      - Email:
          message: Invalid email address.